config/routes.rb
TbdVentures::Application.routes.draw do

  resources :servers 
  resources :restaurants
  resources :users
  
  root "layouts#home"
  
  get "layouts/waiters"

  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	attr_accessible :name, :phone, :street_address, :city, :state, :category, :rating, :cover_photo
	validates :name, presence: true, length: { maximum: 50 }
	validates :phone, presence: true
	validates :street_address, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :category, presence: true
	validates :rating, numericality: true
	has_attached_file :cover_photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	#validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	default_scope -> { order('rating DESC') }
end

app/models/server.rb
class Server < ActiveRecord::Base
	attr_accessible :name, :gender

	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :first_name, :last_name, :username, :email, :password, :password_confirmation, :profile_picture
	has_secure_password
	
	validates :first_name, presence: true, length: { maximum: 20 }
	validates :last_name, presence: true, length: { maximum: 20 }
	validates :username, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	#VALID_PASSWORD_REGEX = /^(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){8,40}$/
	validates :password, presence: true, length: { minimum: 6 } #, format: { with: VALID_PASSWORD_REGEX, multiline: true }
	has_attached_file :profile_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
	#default_scope -> { order('created_at DESC') }
	
	before_save { |user| user.email = email.downcase }
  	#before_create :create_remember_token
	

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

	private
	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def home
  	@restaurants = Restaurant.paginate(page: params[:page], per_page: 5)
  end

  def entities
  end

  def waiters
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
  	@restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params) 
    if @restaurant.save
      flash[:success] = "#{@restaurant.name} created!"
      render 'show'
    else
	    flash[:error] = "#{@restaurant.name} could not be created." 
      render 'new'
    end
  end 

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index 
    @restaurants = Restaurant.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end 

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = "#{@restaurant.name} updated!"
      render 'show'
    else 
      flash[:error] = "#{@restaurant.name} could not be updated." 
      render 'edit' 
    end 
  end 

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :phone, :street_address, :city, :state, :website, :category, :rating)
    end 
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  
	def show
		@server = Server.find(params[:id])
	end

	def index
		@servers = Server.paginate(page: params[:page])
	end

	def edit
		@server = Server.find(params[:id])
	end

	def update
		@server = Server.find(params[:id])
		if @server.update_attributes(server_params)
			flash[:success] = "Your server has been updated!"
			redirect_to @server
		else
			render "edit"
		end
	end



	def destroy
	end

	def create
		@server = Server.new(server_params)
		if @server.save
			flash[:success] = "Thanks for adding a server!"
			redirect_to @server
		else
			render "show"
		end
	end

  	def new
  		@server = Server.new
  	end

  	def server_params
      params.require(:server).permit(:name, :gender)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to TBD #{@user.username}!"
			render 'show'
		else 
			flash[:error] = "#{@user.first_name}, we could not sign you up." 
      		render 'new'
		end
	end 

  	def show
  		@user = User.find(params[:id])
 	end

	def index
		@users = User.paginate(page: params[:page], per_page: 10)
	end

	def edit 
		@user = User.find(params[:id])
	end 

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "#{@user.username} updated!"
			render 'show'
		else 
			flash[:error] = "#{@user.first_name}, we could not update your profile." 
      		render 'edit'
      	end 
	end 

	private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password,
                                   :password_confirmation, :profile_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  	def full_title(page_title)
	    base_title = "TBD Ventures"
	    if page_title.empty?
	      base_title
	    else
	      "#{base_title} | #{page_title}"
	    end
  	end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/servers_helper.rb
module ServersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(server)
    gravatar_id = Digest::MD5::hexdigest(server.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: server.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
      <!-- FOOTER -->
    <div id="footer">
      <div class="container">
        <p class="pull-right text-muted credit">
          <a href="#top">Back to top</a>
        </p>
        <p class="text-muted credit">&copy; 2013 TBD Ventures &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </div>
    </div>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to("TBD Ventures", root_path, class: "navbar-brand") %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><%= link_to("Restaurants", restaurants_path) %> </li>
            <li><li><%= link_to("Users", users_path) %> </li></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <!-- FORM NEEDS TO BE FIXED TO BE RAILS -->
            <form class="form-inline" role="form" id="sign-in-form">
                <div class="form-group">
                  <label class="sr-only" for="exampleInputEmail2">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
                </div>
              <div class="form-group">
                <label class="sr-only" for="exampleInputPassword2">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
              </div>
              <!-- <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me
                </label>
              </div>
               --><button type="submit" class="btn btn-default">Sign in</button>
            </form>
            <small>New to TBD? <strong><%=link_to("Join today &raquo;".html_safe, new_user_path) %></strong></small> </a>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_shim.html.erb
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="wrap">
    <%= render 'layouts/nav_bar' %>   
	  <div class="container">
    	
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
    	<%= yield %>
    
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<a name="top"> </a>
<!-- SPLASH IMAGE & SEARCH BUTTON --> 
<div class="container"> 
  <%= image_tag("restaurant_img_cropped_medium.jpg", :class => "img-responsive", :alt => "Background image", :id => "splash-image") %>
   <form>
    <div class="col-lg-4" id="splash-caption"> 
      <input type="search" class="form-control input-lg" placeholder="Where are you right now?">
      <%= link_to(restaurants_path) do %>
      <button type="button" id="search-button" class="btn btn-primary btn-lg"> Show me what you got</button>
      <% end %>
    </div>
  </form>
</div>

<!-- TOP ENTITIES LIST -->
<a name="top-lists"></a>
<div class="container"> 
    <div class="row"> 
      <div class="col-lg-5 top-lists">
        <table class="table table-hover">
          <thead>
            <h2 class="text-primary text-center"> Top Entities </h2>
          </thead>
          <tbody>
             <% @restaurants.each do |restaurant| %>
          <tr>
            <td><%= image_tag(restaurant.cover_photo.url(:thumb), :class => "img-thumbnail", :alt => "#{restaurant.name} image") %></td>
            <td><%= link_to restaurant.name, restaurant%></td>
            <td><%= restaurant.rating %></td>
          </tr>
            <% end %>
           </tbody>
        </table>
      </div>


      <div class="col-lg-5 col-lg-offset-2 top-lists">
        <table class="table table-hover">
          <thead>
            <h2 class="text-primary text-center"> Top waiters </h2>
          </thead>
          <tbody>
            <tr>
              <td> 1 </td>
              <td> David </td>
            </tr>
            <tr>
              <td> 2 </td>
              <td> Jansen </td>
            </tr>
            <tr>
              <td> 3 </td>
              <td> Lauren </td>
            </tr>
        </table>
      </div>
    </div>
</div>
<!-- /.container -->

    <!--
    <div class="col-lg-6 top-lists">
      <h2 class="text-primary"> Top entities </h2> 
      <ol>
        <li> Dumont </li>
        <li> Kristof </li> 
        <li> Fette Sau </li>  
      </ol>
    </div>     
    -->
    <!--
    <div class="col-lg-6 top-lists pull-right">
      <h2 class="text-primary"> Top waiters </h2> 
      <ol>
        <li> David </li>
        <li> Lauren </li> 
        <li> Jansen </li>  
      </ol>
    </div> 
    -->

app/views/restaurants/_restaurant.html.erb
<!-- <li>
  <%= link_to restaurant.name, restaurant %>
</li>
 -->

app/views/restaurants/edit.html.erb
<% provide(:title, 'Edit restaurant') %>
<div class="container">
	<h2 class="text-primary">Edit restaurant info</h2>
	<div class="col-lg-6">
		<div class="form-group">
			<%= form_for(@restaurant) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control", placeholder: "Restaurant name"%>

			<%= f.label :phone %>
			<%= f.telephone_field :phone, class: "form-control", placeholder: "Restaurant phone number" %>

			<%= f.label :street_address %>
			<%= f.text_field :street_address, class: "form-control", placeholder: "Restaurant address" %>

			<%= f.label :city %>
			<%= f.text_field :city, class: "form-control", placeholder: "Restaurant city" %>

			<%= f.label :state %>
			<%= f.text_field :state, class: "form-control", placeholder: "Restaurant state" %>

			<%= f.label :category %>
			<%= f.text_field :category, class: "form-control", placeholder: "Restaurant category" %>

			<%= f.label :rating %>
			<%= f.text_field :rating, class: "form-control", placeholder: "Restaurant rating" %>
			
			<%= f.label :cover_photo %>	
  			<%= f.file_field :cover_photo %> <br>
		
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
		</div>	
	</div>
</div>

app/views/restaurants/index.html.erb
<% provide(:title, 'All restaurants') %>
<div class="row">

  <div class="col-lg-6 col-lg-offset-2">
    <h1>All restaurants</h1>
    <table class="table table-hover">
      <tr>
        <th></th>
        <th>Name</th>
        <th>Rating</th>
      </tr>

    <% @restaurants.each do |restaurant| %>
      <tr>
        <td>
          <%= link_to(restaurant) do %> 
            <%= image_tag(restaurant.cover_photo.url(:thumb), :class => "img-thumbnail", :alt => "#{restaurant.name} image") %>
          <% end %>
          </td>
        <td><%= link_to restaurant.name, restaurant%></td>
        <td><%= restaurant.rating %></td>
      </tr>
    <% end %>
    </table>
  </div>

  <div class="col-lg-1 col-lg-offset-1">
    <%= link_to(new_restaurant_path) do %>
      <button type="button" class="btn btn-danger">New restaurant?</button>
    <% end %>
  </div>
</div>


<%= will_paginate%>

app/views/restaurants/new.html.erb
<% provide(:title, 'Create new restaurant') %>
<div class="container">
	<h2 class="text-primary">Enter a new restaurant</h2>
	<div class="col-lg-6">
		<div class="form-group">
			<%= form_for(@restaurant) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control", placeholder: "Restaurant name"%>

			<%= f.label :phone %>
			<%= f.telephone_field :phone, class: "form-control", placeholder: "Restaurant phone number" %>

			<%= f.label :street_address %>
			<%= f.text_field :street_address, class: "form-control", placeholder: "Restaurant address" %>

			<%= f.label :city %>
			<%= f.text_field :city, class: "form-control", placeholder: "Restaurant city" %>

			<%= f.label :state %>
			<%= f.text_field :state, class: "form-control", placeholder: "Restaurant state" %>

			<%= f.label :category %>
			<%= f.text_field :category, class: "form-control", placeholder: "Restaurant category" %>

			<%= f.label :rating %>
			<%= f.text_field :rating, class: "form-control", placeholder: "Restaurant rating" %>
			
			<%= f.label :cover_photo %>	
  			<%= f.file_field :cover_photo %> <br>
		
		<%= f.submit "Create", class: "btn btn-large btn-primary" %>
		<% end %>
		</div>	
	</div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, "#{@restaurant.name}") %>
<div class="row"> 
	<div class="col-lg-6"> 
		<%= image_tag(@restaurant.cover_photo.url, :class => "img-responsive", :alt => "#{@restaurant.name} image", :id => "restaurant-show-image") %>
	</div>

	<div class="col-lg-6">
		<div class="pull-right">
      <%= link_to(new_restaurant_path) do %>
        <button type="button" class="btn btn-danger">New restaurant?</button>
      <% end %>
    </div>
    
    <h1 class="profile-heading"> 
      <%= @restaurant.name %> 
      <div class="col-lg-offset-4 rating-bubble"> <%= @restaurant.rating %></div>
    </h1> 
		
    <h4> 
      <%= @restaurant.category %> 
      <p class="text-muted pull-right"><%= link_to("Edit restaurant info", edit_restaurant_path(@restaurant)) %> </p>
    </h4> 
		
    <h5> 
			<%= @restaurant.street_address %> <br>
			<%= @restaurant.city %>, <%= @restaurant.state %> </br>
			<%= @restaurant.phone %>
		</h5>

		<table class="table table-hover">
          <thead>
            <h2> Top waiters </h2>
          </thead>
          <tbody>
            <tr>
              <td> 1 </td>
              <td> David </td>
            </tr>
            <tr>
              <td> 2 </td>
              <td> Jansen </td>
            </tr>
            <tr>
              <td> 3 </td>
              <td> Lauren </td>
            </tr>
        </table>
	</div>

  

</div>

app/views/servers/edit.html.erb
<% provide(:title, "Edit server") %>
<h1>Update your server information</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@server) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :gender %>
      <%= f.text_field :gender %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/servers/index.html.erb
<% provide(:title, 'All servers') %>
<h1>All servers</h1>

<%= will_paginate %>

<ul class="servers">
  <% @servers.each do |server| %>
    <li>
      <%= link_to server.name, server %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/servers/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@server) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
      	<%= f.label :name %>
      	<%= f.text_field :name %>

      	<%= f.label :gender %>
      	<%= f.text_field :gender %>

      <%= f.submit "Create new server", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<% provide(:title, 'Add server') %>
<h1>Add Server</h1>

app/views/servers/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @server.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
			
<%= f.label :username %>
<%= f.text_field :username, class: "form-control", placeholder: "Username"%>

<%= f.label :password %>
<%= f.password_field :password, class: "form-control", placeholder: "Password" %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>

<%= f.label :first_name %>
<%= f.text_field :first_name, class: "form-control", placeholder: "First name"%>

<%= f.label :last_name %>
<%= f.text_field :last_name, class: "form-control", placeholder: "Last name" %>

<%= f.label :email %>
<%= f.text_field :email, class: "form-control", placeholder: "Email" %>

<%= f.label :cover_photo%>	
<%= f.file_field :cover_photo %> <br>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="container">
	<h2 class="text-primary">Update your profile</h2>
	<div class="col-lg-6">
		<div class="form-group" id="user-info-form">
			<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
		</div>	
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="row">

<div class="col-lg-8 col-lg-offset-1">
  <h1>All users</h1>
  <table class="table table-hover">
    <tr>
      <th></th>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      
      <td>
        <%= link_to(user) do %> 
          <%= image_tag(user.profile_picture.url(:thumb), :class => "img-thumbnail", :alt => "#{user.username} image") %>
        <% end %>
      </td>
      <td><%= link_to user.username, user%></td>
      <td><%= link_to user.first_name, user%></td>
      <td><%= link_to user.last_name, user%></td>
      <td><%= mail_to user.email %></td>                  
    </tr>
  <% end %>
  </table>
  </div>
</div>

<%= will_paginate%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
	<h2 class="text-primary">Sign up</h2>
	<div class="col-lg-6">
		<div class="form-group" id="user-info-form">
			<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
		</div>	
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row"> 
	<div class="col-lg-6"> 
		<%= image_tag(@user.profile_picture.url, :class => "img-responsive", :alt => "#{@user.username} image", :id => "restaurant-show-image") %>
	</div>

	<div class="col-lg-6">
		<h1 class="profile-heading"> <%= @user.first_name %> <%= @user.last_name %></h1> 
		<h4> 
      <%= @user.username %> 
      <p class="text-muted pull-right"><%= link_to("Edit user", edit_user_path(@user)) %> </p>
    </h4> 
		<h5> <%= @user.email %> </h5>

		<table class="table table-hover">
          <thead>
            <h2> Top waiters </h2>
          </thead>
          <tbody>
            <tr>
              <td> 1 </td>
              <td> David </td>
            </tr>
            <tr>
              <td> 2 </td>
              <td> Jansen </td>
            </tr>
            <tr>
              <td> 3 </td>
              <td> Lauren </td>
            </tr>
        </table>
	</div>
</div>